import { test, expect } from '@playwright/test';
import { readFile, mkdir } from 'node:fs/promises';
import { parseEnv } from 'node:util';

const secrets = parseEnv(await readFile('.dev.vars', 'utf8'));
const command = async (page, value) => {
  const input = page.getByRole('textbox', { name: 'Terminal command', exact: true });
  await input.fill(value);
  await input.press('Enter');
  await expect(page.locator('#command')).toBeEnabled();
};

test('tree, grouping, inline markdown, deep links, and terminal', async ({ page }) => {
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.emulateMedia({ colorScheme: 'dark' });
  await page.goto('/');
  await expect(page.locator('#summary')).toHaveText('0 directories, 6 files');
  await expect(page.getByRole('button', { name: 'Edit tomfoolery.md', exact: true })).toHaveCount(0);
  await page.getByRole('link', { name: 'tomfoolery.md', exact: true }).click();
  await expect(page).toHaveURL(/#\/tomfoolery\.md$/);
  await expect(page.getByRole('heading', { name: 'tomfoolery' })).toBeVisible();
  await page.getByRole('button', { name: 'Toggle raw markdown' }).click();
  await expect(page.locator('.file-view pre')).toContainText('# tomfoolery');
  await page.reload();
  await expect(page.getByRole('heading', { name: 'tomfoolery' })).toBeVisible();
  await page.getByRole('button', { name: 'type', exact: true }).click();
  await expect(page.locator('#summary')).toHaveText('4 directories, 6 files');
  await expect(page.locator('.file-view')).toHaveClass(/nested/);
  await page.getByRole('button', { name: 'genre', exact: true }).click();
  await expect(page.locator('.tree-folder').last()).toHaveText('└── unknown/');
  await command(page, 'group nonsense');
  await expect(page.locator('#history')).toContainText('valid keys: none');
  await command(page, 'cat wavesay');
  await expect(page.locator('#history')).toContainText('name: wavesay');
  await command(page, 'new nope');
  await expect(page.locator('#history')).toContainText('permission denied. try sudo.');
  await command(page, 'missing-command');
  await expect(page.locator('#history')).toContainText('missing-command: command not found. try help');
  await command(page, 'sudo');
  await expect(page.getByLabel('Passphrase', { exact: true })).toHaveAttribute('type', 'password');
  await page.getByLabel('Passphrase', { exact: true }).press('Escape');
  await command(page, 'clear');
  await expect(page.locator('#history')).toBeEmpty();
  await command(page, 'close');
  await command(page, 'group none');
  await command(page, 'clear');
  await page.getByRole('textbox', { name: 'Terminal command', exact: true }).blur();
  await mkdir('.artifacts', { recursive: true });
  await page.setViewportSize({ width: 909, height: 540 });
  await page.screenshot({ path: '.artifacts/desktop-dark.png' });
  for (const colorScheme of ['dark', 'light']) {
    await page.emulateMedia({ colorScheme });
    await page.setViewportSize({ width: 375, height: 812 });
    await page.getByRole('link', { name: 'tomfoolery.md', exact: true }).click();
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    await page.screenshot({ path: `.artifacts/mobile-${colorScheme}.png`, fullPage: true });
    await page.getByRole('button', { name: 'Close tomfoolery.md' }).click();
  }
  expect(errors).toEqual([]);
});

test('admin login, validation, CRUD persistence, README protection, logout', async ({ page, request }) => {
  const path = `test-${Date.now()}.md`;
  await page.goto('/');
  await expect(page.locator('#summary')).toHaveText('0 directories, 6 files');
  await command(page, 'sudo');
  const input = page.getByLabel('Passphrase', { exact: true });
  await input.fill(secrets.ADMIN_PASSPHRASE);
  await input.press('Enter');
  await expect(page.locator('#history')).toContainText('ok. you can edit now.');
  await expect(page.locator('#prompt-label')).toHaveText('# ');
  const cookies = await page.context().cookies();
  const session = cookies.find(cookie => cookie.name === 'metashelf_session');
  expect(session.httpOnly).toBe(true);
  expect(session.sameSite).toBe('Strict');
  await expect(page.getByRole('button', { name: 'Delete README.md', exact: true })).toHaveCount(0);
  await page.getByRole('button', { name: '+ new.md', exact: true }).click();
  await page.getByRole('textbox', { name: 'File name', exact: true }).fill(path);
  await page.getByRole('textbox', { name: 'Name', exact: true }).fill('test project');
  await page.getByRole('textbox', { name: 'Url', exact: true }).fill('example.com');
  await page.getByRole('textbox', { name: 'Title', exact: true }).fill('Test project');
  await page.getByRole('textbox', { name: 'Body', exact: true }).fill('First paragraph.\n\nSecond paragraph.');
  await page.getByRole('textbox', { name: 'Tags JSON', exact: true }).fill('[]');
  await page.getByRole('button', { name: ':wq save', exact: true }).click();
  await expect(page.getByRole('alert')).toContainText('tags must be a JSON object');
  await page.getByRole('textbox', { name: 'Tags JSON', exact: true }).fill('{"custom tag":"custom value","type":"test"}');
  await page.getByRole('button', { name: ':wq save', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Test project' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'custom tag', exact: true })).toBeVisible();
  await page.reload();
  await expect(page.getByRole('heading', { name: 'Test project' })).toBeVisible();
  await page.getByRole('button', { name: `Edit ${path}`, exact: true }).click();
  await page.getByRole('textbox', { name: 'Body', exact: true }).fill('Updated paragraph.');
  await page.getByRole('button', { name: ':wq save', exact: true }).click();
  await expect(page.locator('.file-view')).toContainText('Updated paragraph.');
  await page.reload();
  await expect(page.locator('.file-view')).toContainText('Updated paragraph.');
  await page.getByRole('button', { name: 'Edit README.md', exact: true }).click();
  await expect(page.locator('.editor textarea')).toHaveCount(1);
  await expect(page.locator('.editor input')).toHaveCount(0);
  await page.getByRole('button', { name: ':q! cancel', exact: true }).click();
  const authHeaders = { Cookie: `metashelf_session=${session.value}` };
  expect((await request.delete('/api/files/README.md', { headers: authHeaders })).status()).toBe(403);
  expect((await request.put(`/api/files/${path}`, { headers: { ...authHeaders, 'If-None-Match': '*' }, data: { raw: 'bad' } })).status()).toBe(409);
  expect((await request.put(`/api/files/${path}`, { headers: authHeaders, data: { raw: 'bad' } })).status()).toBe(400);
  expect((await request.put(`/api/files/${path}`, { headers: { ...authHeaders, Origin: 'https://elsewhere.invalid' }, data: { raw: 'bad' } })).status()).toBe(403);
  await page.getByRole('button', { name: `Delete ${path}`, exact: true }).click();
  await expect(page.getByRole('button', { name: `Delete ${path}`, exact: true })).toHaveText('delete? yes');
  await page.getByRole('button', { name: `Delete ${path}`, exact: true }).click();
  await expect(page.getByRole('link', { name: path, exact: true })).toHaveCount(0);
  await page.reload();
  await expect(page.locator('#summary')).toHaveText('0 directories, 6 files');
  await command(page, 'logout');
  await expect(page.locator('#prompt-label')).toHaveText('$ ');
  expect((await request.put('/api/files/no.md', { data: { raw: 'bad' } })).status()).toBe(401);
  expect((await request.delete('/api/files/tomfoolery.md')).status()).toBe(401);
});

test('wrong passphrase is rejected and attempts are rate limited', async ({ request }) => {
  const statuses = [];
  for (let i = 0; i < 6; i++) statuses.push((await request.post('/api/auth', { data: { passphrase: 'incorrect-test-passphrase' } })).status());
  expect(statuses).toContain(401);
  expect(statuses.at(-1)).toBe(429);
});
